version: '3'
services:

  namenode:
    build: ./namenode
    volumes:
      - ./conf:/opt/hadoop-3.3.1/etc/hadoop
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop-net

  datanode:
    build: ./datanode
    volumes:
      - ./conf:/opt/hadoop-3.3.1/etc/hadoop
    ports:
      - "9864:9864"
    networks:
      - hadoop-net

  #nodemanager:
  #  build: ./datanode
  #  volumes:
  #    - ./conf:/opt/hadoop-3.3.1/etc/hadoop
  #  ports:
  #    - "9864:9864"
  #  networks:
  #    - hadoop-net


  spark:
    build: ./spark
    #volumes:
     # - ./conf/spark:/spark/conf
    ports:
      - "4040:4040"
    networks:
      - hadoop-net

networks:
  hadoop-net:
