version: '3'
services:

  namenode:
    build: ./namenode
    container_name: namenode
    volumes:
      - ./conf:/opt/hadoop-3.3.1/etc/hadoop
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop-net

  datanode:
    build: ./datanode
    container_name: datanode
    depends_on:
      - namenode
    volumes:
      - ./conf:/opt/hadoop-3.3.1/etc/hadoop
    ports:
      - "9864:9864"
    networks:
      - hadoop-net

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    hostname: sparkmaster
    networks:
      - hadoop-net
    volumes:
      - ../src/scala:/opt/spark
    ports:
      - "8090:8080"
      - "7077:7077"
    environment:
    - JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
    - INIT_DAEMON_STEP=setup_spark
    working_dir: /spark/bin

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    networks:
      - hadoop-net
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=sparkmaster:7077

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    networks:
      - hadoop-net
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=sparkmaster:7077

networks:
  hadoop-net:
    external: true